name: Build image for Release channel
on:
  workflow_dispatch:
    inputs:

      build_base:
        type: choice
        description: 'Base Distribution'
        required: false
        options:
        - debian
        - ubuntu
        default: debian

      build_flavour:
        type: choice
        description: 'Flavour'
        required: false
        options:
        - cli
        - kde
        - xfce
        default: cli

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: b${{ github.run_number }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        boards: [rock-pi-4b]
        build_systems: [rbuild]
        distros: ["${{inputs.build_base}}"]
        flavors: ["${{inputs.build_flavour}}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload rbuild image
        uses: radxa-repo/rbuild@main
        if: matrix.build_systems == 'rbuild'
        with:
          board: ${{ matrix.boards }}
          distro: ${{ matrix.distros }}
          flavor: ${{ matrix.flavors }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
